[package]
name = "terracotta"
version = "0.1.0"
authors = ["Wisnu Adi Nurcahyo <wisn.adn@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7.18"
serde = { version = "1.0.89", features = ["derive"] }
